/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alex_db;

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author asdfas
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Update(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        NameLabel = new java.awt.Label();
        NameTextField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        NameLabel1 = new java.awt.Label();
        label2 = new java.awt.Label();
        GameUpdate = new javax.swing.JComboBox();
        DateLabel2 = new java.awt.Label();
        FromYear = new javax.swing.JComboBox();
        FromMonth = new javax.swing.JComboBox();
        FromDay = new javax.swing.JComboBox();
        SaveUpdateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DeleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Kliento informacijos keitimas");

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDLabel.setText("ID");

        NameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NameLabel.setText("Vardas");

        NameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameTextField.setMinimumSize(new java.awt.Dimension(100, 25));
        NameTextField.setPreferredSize(new java.awt.Dimension(100, 25));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        LastNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LastNameField.setMinimumSize(new java.awt.Dimension(100, 25));
        LastNameField.setPreferredSize(new java.awt.Dimension(100, 25));

        NameLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        NameLabel1.setText("Pavardė");

        label2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label2.setText("Žaidimas");

        GameUpdate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GameUpdate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Crash Bandicoot", "Counter Strike", "Marijo", "Bioshock Infinite", "Amnesia", "Dead Space", "Hitman", "Prince of Persia", "Need for Speed", "Shrek 2" }));
        GameUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GameUpdateActionPerformed(evt);
            }
        });

        DateLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DateLabel2.setText("Užsakymo data");

        FromYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020" }));

        FromMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sausis", "Vasaris", "Kovas", "Balandis", "Gegužė", "Birželis", "Liepa", "Rugpjūtis", "Rugsėjis", "Spalis", "Lapkritis", "Gruodis", " " }));

        FromDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        SaveUpdateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SaveUpdateBtn.setText("Išsaugoti pakeitimus");
        SaveUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveUpdateBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("KlientoID:");

        DeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteBtn.setText("Trinti");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(GameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(DateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaveUpdateBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FromYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(FromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(FromDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDLabel)))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DeleteBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(SaveUpdateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void GameUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GameUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GameUpdateActionPerformed

    private void SaveUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveUpdateBtnActionPerformed

        int ID = Integer.parseInt(IDLabel.getText());
        String Vardas = NameTextField.getText().toString();
        String Pavarde = LastNameField.getText().toString();
        String Zaidimas = GameUpdate.getSelectedItem().toString();
        String Data = "";
        String MenuoF = FromMonth.getSelectedItem().toString();
        String Menuo="";

            switch(MenuoF)
            {
                case "Sausis": Menuo = "01"; break; case "Vasaris": Menuo = "02"; break; case "Kovas": Menuo = "03"; break; 
                case "Balandis": Menuo = "04"; break; case "Gegužė": Menuo = "05"; break; case "Birželis": Menuo = "06"; break; 
                case "Liepa":  Menuo = "07"; break; case "Rugpjūtis":  Menuo = "08"; break; case "Rugsėjis": Menuo = "09"; break; 
                case "Spalis":  Menuo = "10"; break; case "Lapkritis":  Menuo = "11"; break; case "Gruodis": Menuo = "12"; break; 
            }
        
        Data = FromYear.getSelectedItem().toString()+"-"+ Menuo +"-"+FromDay.getSelectedItem().toString();
            
        if(NameTextField.getText().length()==0 || LastNameField.getText().length()==0)
        {
            JOptionPane.showMessageDialog(new JFrame(), "Neteisingai įvesti duomenys", "Klaida", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String UPDATEclient = "UPDATE Naudotojas SET Vardas = '" + Vardas +"', Pavarde = '" + Pavarde + "' WHERE Kliento_Nr = " + ID+"\n";
                        
        String UpdateData = "UPDATE Uzsakymas SET Uzsakymas.Uzsakymo_Data ='" + Data + "' WHERE Uzsakymas.Kliento_Nr = "+ ID +"\n"; 
        
        System.out.println(UPDATEclient);
        
        System.out.println(UpdateData);

        
        Connection con = null;

        try {

            SQLServerDataSource ds = new SQLServerDataSource();
              ds.setServerName("localhost");
              ds.setPortNumber(1433);
              ds.setDatabaseName("Alekxxx");
              ds.setUser("aleksandra");
              ds.setPassword("");
              
              con = ds.getConnection();

            Statement statement = con.createStatement();

            statement.executeUpdate(UPDATEclient);
            statement.executeUpdate(UpdateData);

        }
        catch(SQLException e){e.printStackTrace();}

        Update.this.dispose();
    }//GEN-LAST:event_SaveUpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        
        int ID = Integer.parseInt(IDLabel.getText());
        
     
        
        
        Connection con = null;
                       
        if (JOptionPane.showConfirmDialog(null, "Are norite trinti klienta #"+ID+"?", "WARNING", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
        {
               
          try {
                   
              String DELETEclient = "DELETE FROM Naudotojas WHERE Kliento_Nr = "+ ID;
               String DELETEsudaro="";
              String DELETEuzsakymas = "DELETE FROM Uzsakymas WHERE Kliento_Nr = "+ ID;
            
              SQLServerDataSource ds = new SQLServerDataSource();
              ds.setServerName("localhost");
              ds.setPortNumber(1433);
              ds.setDatabaseName("Alekxxx");
              ds.setUser("aleksandra");
              ds.setPassword("");
                        
            con = ds.getConnection();
            
            Statement statement = con.createStatement();
            
            String GetUzsakymoID = "SELECT Uzsakymas.Uzsakymo_Nr FROM UZSAKYMAS WHERE Kliento_Nr = " +ID;
            
            ResultSet set = statement.executeQuery(GetUzsakymoID);
                        
            while(set.next())
            {
                int UzsakymoID = set.getInt("Uzsakymo_Nr");
                DELETEsudaro = "DELETE from Sudaro WHERE Uzsakymo_Nr = "+UzsakymoID;
            }
            
            
            statement.executeUpdate(DELETEsudaro);
            statement.executeUpdate(DELETEuzsakymas);
            statement.executeUpdate(DELETEclient);
            
        }
        catch(SQLException e){e.printStackTrace();}
               
               Update.this.dispose();
               JOptionPane.showMessageDialog(new JFrame(), "Klientas #"+ID+" istrintas", "Info", JOptionPane.ERROR_MESSAGE);
        }
        else{Update.this.dispose();}
         
        Update.this.dispose();
        
    }//GEN-LAST:event_DeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Update dialog = new Update(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public java.awt.Label DateLabel2;
    public javax.swing.JButton DeleteBtn;
    public javax.swing.JComboBox FromDay;
    public javax.swing.JComboBox FromMonth;
    public javax.swing.JComboBox FromYear;
    public javax.swing.JComboBox GameUpdate;
    public javax.swing.JLabel IDLabel;
    public javax.swing.JTextField LastNameField;
    private java.awt.Label NameLabel;
    private java.awt.Label NameLabel1;
    public javax.swing.JTextField NameTextField;
    public javax.swing.JButton SaveUpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
